# Generated by Django 5.1.1 on 2025-12-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(choices=[(1, 'Muy malo'), (2, 'Malo'), (3, 'Bueno'), (4, 'Muy bueno'), (5, 'AOTY')]),
        ),
    ]
