# Generated by Django 5.1.1 on 2025-02-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_bio_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notifGenerales',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notifPorMail',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notifRecomendaciones',
            field=models.BooleanField(default=1),
        ),
    ]
