# Generated by Django 5.1.1 on 2025-11-06 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_log_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.FloatField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('request_body', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-datetime']},
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['logtype', 'datetime'], name='logger_log_logtype_d6b948_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['datetime'], name='logger_log_datetim_3c211c_idx'),
        ),
        migrations.AddField(
            model_name='apimonitor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apimonitor',
            index=models.Index(fields=['timestamp'], name='logger_apim_timesta_63697d_idx'),
        ),
        migrations.AddIndex(
            model_name='apimonitor',
            index=models.Index(fields=['status_code', 'timestamp'], name='logger_apim_status__8579bd_idx'),
        ),
        migrations.AddIndex(
            model_name='apimonitor',
            index=models.Index(fields=['endpoint', 'timestamp'], name='logger_apim_endpoin_5f3720_idx'),
        ),
        migrations.AddIndex(
            model_name='apimonitor',
            index=models.Index(fields=['method', 'timestamp'], name='logger_apim_method_b9830d_idx'),
        ),
    ]
