# Generated by Django 5.1.1 on 2025-02-05 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_notificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 2, 5)),
        ),
    ]
