# Generated by Django 5.1.1 on 2024-10-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('length', models.DurationField()),
                ('country', models.CharField(max_length=50)),
                ('released', models.BooleanField(default=False)),
                ('playcount', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
