# Generated by Django 5.1.1 on 2024-10-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='country',
        ),
        migrations.RemoveField(
            model_name='album',
            name='released',
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
