# Generated by Django 5.1.1 on 2024-09-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='playcount',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
