# Generated by Django 5.1.1 on 2024-11-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='releaseDate',
            field=models.DateField(null=True),
        ),
    ]
