# Generated by Django 5.1.1 on 2024-11-16 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_releasedate'),
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artistas.artista'),
            preserve_default=False,
        ),
    ]
